USE [LegalDB]
GO
/****** Object:  Table [dbo].[Executors_tb]    Script Date: 10/26/2020 05:41:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Executors_tb](
	[TID] [int] IDENTITY(1,1) NOT NULL,
	[ReviewID] [int] NOT NULL,
	[Login] [varchar](50) NOT NULL,
	[Status] [int] NULL,
	[RD] [datetime] NULL,
 CONSTRAINT [PK_Executors_TID] PRIMARY KEY CLUSTERED 
(
	[TID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [WX_Executors_ReviewID] ON [dbo].[Executors_tb] 
(
	[ReviewID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Executors_tb]  WITH CHECK ADD  CONSTRAINT [FK_Executors_ReviewID] FOREIGN KEY([ReviewID])
REFERENCES [dbo].[Reviews_tb] ([TID])
GO
ALTER TABLE [dbo].[Executors_tb] CHECK CONSTRAINT [FK_Executors_ReviewID]
GO
ALTER TABLE [dbo].[Executors_tb] ADD  CONSTRAINT [DF_Executors_RD]  DEFAULT (getdate()) FOR [RD]
GO
